### ISSUE TITLE
No `requirements.txt`.

### ISSUE THREAD

**Issue by qw3rtman** [defaultnamehere/zzzzz#1]
I might be missing something here, but shouldn't there be a `requirements.txt` file?

Running `pip install -r requirements.txt` gives me:

```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by defaultnamehere** [comment]
tfw forgot to commit that. My bad, I'll commit it in a bit

**Comment by qw3rtman** [comment]
No worries. Thanks!

**Comment by davidfurlong** [comment]
+1

**Comment by csu** [comment]
:+1:

**Comment by tgxn** [comment]
+1

**Comment by defaultnamehere** [comment]
Manual "workaround" until I can re-generate the requirements.

`pip3 install flask requests`

P.S. I literally typed this in a browser without running it so no promises that it's completely correct

**Comment by tgxn** [comment]
I installed requests using `pip install requests` and it's running for me now.

Are there any further requirements for the graphing/server?

Edit: Flask, duh!

**Comment by jczimm** [comment]
+1

**Comment by vidia** [comment]
+1

**Comment by adamowen** [comment]
Can you please commit requirements.txt?
