### ISSUE TITLE
Can't generate .csv files: No such file or directory: 'log/.txt'

### ISSUE THREAD

**Issue by MindaugasJucius** [defaultnamehere/zzzzz#16]
Trying to run 
`python graph.py`
yields the following error
`Traceback (most recent call last):
  File "graph.py", line 64, in <module>
    g.generate_all_csvs(start_time=now - 3 * ONE_DAY_SECONDS, end_time=now)
  File "graph.py", line 56, in generate_all_csvs
    self.to_csv(uid, start_time, end_time)
  File "graph.py", line 27, in to_csv
    status_history = history.StatusHistory(uid)
  File "/Users/vinted/Documents/zzzzz-master/history.py", line 18, in __init__
    with open("log/{uid}.txt".format(uid=uid)) as f:
IOError: [Errno 2] No such file or directory: 'log/.txt'`
A workaround is to replace {uid} with a concrete uid

**Comment by defaultnamehere** [comment]
You need to first collect some data with `python3 fetcher.py`.

**Comment by MindaugasJucius** [comment]
well I have done that

**Comment by MindaugasJucius** [comment]
ok, downloaded again and now it works
