### ISSUE TITLE
"cookie=<Contains your Facebook cookie>"

### ISSUE THREAD

**Issue by TheHades** [defaultnamehere/zzzzz#17]
Hi,
uhm..
Do you have an example for this cookie?
I have several entries in my "facebook cookie" ;)

Thanks,

**Comment by emilstahl** [comment]
I just copied a random request as curl and used the whole `cookie:`

**Comment by TheHades** [comment]
Hm. this make sense. 
Thanks!

**Comment by ghost** [comment]
I can't find it -_-

I had no problem finding the 2 IDs, but I can't find the cookie.
