### ISSUE TITLE
"cookie=<Contains your Facebook cookie>"

### ISSUE THREAD

**Issue by ghost** [defaultnamehere/zzzzz#20]
I can't find it -_-

I had no problem finding the 2 IDs, but I can't find the cookie.

**Comment by TheHades** [comment]
Hi,

-open facebook.com
-Press F12 (Google Chrome)
-Click on the "Network"-Tab
-Look for the entry called "pull?....."
-Click on this entry
-There you will find field called "cookie"

**Comment by ghost** [comment]
Now I feel stupid that I didn't see it.
Anyways, thanks!
