### ISSUE TITLE
how to get client_id?

### ISSUE THREAD

**Issue by ParvJain** [defaultnamehere/zzzzz#27]
when I load `facebook.com/pull` It says Page not found, neither I get `client_id` in browser GET request, am I missing something?

**Comment by 0xB455** [comment]
1) open the developer toolbar in your browser (google for hotkeys)
2) go to the netgraph section of the toolbar and activate it
3) enter the facebook.com URL in your browser and log in
4) now observe the net view in the developer toolbar and see the HTTP requests going from your browser towards one of the loadbalancer hosts of facebook (e.g. 5-edge-chat.facebook.com/pull?channel=foobar) - eventuall search for "pull" within the viewstate of your toolbar and you will find it easily

**Comment by ParvJain** [comment]
@TheBazZz thanks, this helped :)
