### ISSUE TITLE
KeyError: 'p' :: Did facebook's internal API change?

### ISSUE THREAD

**Issue by klvs** [defaultnamehere/zzzzz#41]
Hey, cool project. I used it a monthish ago to gather some data and it work great. However, now when I try to use it (after replacing my cookie with a more recent one), I get a json blob with what I assume is the expected data and then immediately the error:

``` bash
Traceback (most recent call last):
  File "fetcher.py", line 175, in <module>
    f.start_request()
  File "fetcher.py", line 124, in start_request
    user_data.append(json.dumps(item["overlay"][uid]["p"]))
KeyError: 'p'
```

Thoughts? Any tips on how to fix this or where to look? I'm using it for a data vis project and while I'm too busy to fix it right now, I could submit a PR in the near future.

**Comment by tovabbi** [comment]
@klvs this solved here: https://github.com/defaultnamehere/zzzzz/issues/38, you can delete your issue

**Comment by klvs** [comment]
@tovabbi I tried what's mentioned in #38 without success. I'll try it again, but is there an open PR or fork?
