### ISSUE TITLE
How to run the scripts in background without having to keep terminal open

### ISSUE THREAD

**Issue by srijansaxena11** [defaultnamehere/zzzzz#54]
I tried:
`python /home/openhabian/zzzzz/fetcher.py &`
But it didn't work. Even 
`python /home/openhabian/zzzzz/fetcher.py` 
says 
`SECRETS.txt: no such file or directory`
I have to manually navigate to zzzzz folder using cd command and then run
`python fetcher.py `
in order to make it run
Same goes for other scripts. How to run them in background?

**Comment by pielco11** [comment]
Because `fetcher.py` tries to open a file that should exist in the same directory where you are running the script.  Running `python /home/openhabian/zzzzz/fetcher.py` will open try to open `/SECRETS.txt`

**Comment by srijansaxena11** [comment]
So manually navigating to zzzzz and then running
`sudo python fetcher.py &` 
should allow it to run in background even after the terminal is closed. Right?

**Comment by pielco11** [comment]
There is no need to run with `sudo`. If you close the terminal, the script stops

**Comment by srijansaxena11** [comment]
nvm i found i can use it with nohup as:
`nohup python fetcher.py &`
