### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by sayginburak** [defaultnamehere/zzzzz#8]
When I run pip install -r requirements.txt
gives this error

my requirements.txt:
requests==2.9.1
Flask==0.10.1

Downloading/unpacking requests==2.9.1 (from -r requirements.txt (line 1))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Downloading/unpacking Flask==0.10.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded
  Running setup.py (path:/tmp/pip_build_deploy/Flask/setup.py) egg_info for package Flask

```
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes/.git'
```

Downloading/unpacking Werkzeug>=0.7 (from Flask==0.10.1->-r requirements.txt (line 2))
  Downloading Werkzeug-0.11.4-py2.py3-none-any.whl (305kB): 305kB downloaded
Downloading/unpacking Jinja2>=2.4 (from Flask==0.10.1->-r requirements.txt (line 2))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking itsdangerous>=0.21 (from Flask==0.10.1->-r requirements.txt (line 2))
  Downloading itsdangerous-0.24.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip_build_deploy/itsdangerous/setup.py) egg_info for package itsdangerous

```
warning: no previously-included files matching '*' found under directory 'docs/_build'
```

Downloading/unpacking MarkupSafe (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 2))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_deploy/MarkupSafe/setup.py) egg_info for package MarkupSafe

Installing collected packages: requests, Flask, Werkzeug, Jinja2, itsdangerous, MarkupSafe
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Can't roll back requests; was not uninstalled
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/requests-2.9.1.dist-info'

Storing debug log for failure in /home/deploy/.pip/pip.log

**Comment by Scriptkiddi** [comment]
this means that you already have the dependecies installed propaly via your package manager and now pip can not overwrite them try skipping the pip install step and see if that works

**Comment by sayginburak** [comment]
when I skip pip install the output is:

Traceback (most recent call last):
  File "fetcher.py", line 6, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by Scriptkiddi** [comment]
then do pip install requests

**Comment by Scriptkiddi** [comment]
oh i mean sudo pip install requests

**Comment by sayginburak** [comment]
> > sudo pip install requests 
> > Requirement already satisfied (use --upgrade to upgrade): requests in /Library/Python/2.7/site-packages
> > Cleaning up...

but I managed to run on my remote server. But now I have another issue;
it says Running on http://0.0.0.0:5000/
when I visit the http://server_ip:5000/ I just see a blank white page but server is seemed working

local_ip - - [19/Feb/2016 11:11:47] "GET / HTTP/1.1" 200 -
local_ip - - [19/Feb/2016 11:11:47] "GET /static/css/nv.d3.min.css HTTP/1.1" 200 -
local_ip - - [19/Feb/2016 11:11:47] "GET /static/js/nv.d3.min.js HTTP/1.1" 200 -
local_ip - - [19/Feb/2016 11:11:49] "GET /favicon.ico HTTP/1.1" 404 -
local_ip - - [19/Feb/2016 11:11:50] "GET / HTTP/1.1" 200 -

**Comment by Scriptkiddi** [comment]
have you run the fetcher for a while and then graph.py?

**Comment by sayginburak** [comment]
I ran fetcher.py just for 20-30 seconds, I will try running more.

**Comment by Scriptkiddi** [comment]
check if there is anything in generated_graphs/csv/ ?

**Comment by sayginburak** [comment]
yes there are many csv files in generated_graphs/csv/ but web app is still blank white page.

**Comment by Scriptkiddi** [comment]
enter a uid into the search field if the server reports method not allowed grap the changes from the pull request patch 1 should do the trick

**Comment by sayginburak** [comment]
I tried pacth 1 branch but didn't do the trick :|

**Comment by neutralinsomniac** [comment]
Have you tried scrolling down? For me, the text box is at the very bottom of the page past the bounds of my screen

**Comment by Scriptkiddi** [comment]
try my fork i had some problems in the beginning too but i fixed them
https://github.com/Scriptkiddi/zzzzz

**Comment by sayginburak** [comment]
@neutralinsomniac yes scrolling down works :+1: thanks, both of you
